# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-webapp-deployment
  labels:
    app: webappb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webappb
  template:
    metadata:
      labels:
        app: webappb
    spec:
      containers:
      - name: webappb
        image: {{ .Values.webapp2 }}
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: apache-webapp-service
  labels:
    app: webappb
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /webappb/index.html
spec:
  type: NodePort
  selector:
    app: webappb
  ports:
    - port: 80
      targetPort: 80