apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-webapp-deployment
  namespace: default  
  labels:
    app: webappb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webappb
  template:
    metadata:
      labels:
        app: webappb
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: webappb
        image: {{ .Values.webapp2 }}  
        ports:
        - containerPort: 80  
---
apiVersion: v1
kind: Service
metadata:
  name: apache-webapp-service
  namespace: default 
  labels:
    app: webappb
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /webappb/index.html 
spec:
  type: ClusterIP     
  selector:
    app: webappb
  ports:
    - port: 80         
      targetPort: 80   