apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: default  
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: {{ .Values.webapp1 }}  
        ports:
        - containerPort: 80   
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: default  
  labels:
    app: webapp
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /webapp/index.html  # Health check path for ALB
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 80   
  type: ClusterIP    

