apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app1
  namespace: default  
spec:
  revisionHistoryLimit: 2 
  replicas: 1
  selector:
    matchLabels:
      app: react-app1
  template:
    metadata:
      labels:
        app: react-app1
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: react-app1
          image: {{ .Values.reactapp }}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: default  
spec:
  selector:
    app: react-app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
