apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: {{ .Values.webapp1 }}
        ports:
        - containerPort: 5000  
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
  app: webapp
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /webapp/index.html
spec:
  type: NodePort  
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 5000
