---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: {{ .Values.webapp1 }}  # Your Helm value for the image
        ports:
        - containerPort: 80   # Expose port 80 inside the container
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: default
  labels:
    app: webapp
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /webapp/index.html  # Health check path for ALB
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80          # Expose the service on port 80
      targetPort: 80    # Direct traffic to container port 80
  type: ClusterIP     # Prefer ClusterIP for internal cluster access


