apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: default  
spec:
  revisionHistoryLimit: 2 
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: backend-api
          image: {{ .Values.backend }}
          ports:
            - containerPort: 5000
                  resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
  namespace: default  
spec:
  selector:
    app: backend-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
