apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  namespace: default  
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: k8s-default-myreleas-45dbd5ab2e-34ef1aac88c79d8a.elb.us-east-1.amazonaws.com
      http:
        paths:
          - path: /webapp
            pathType: Prefix
            backend:
              service:
                name: webapp-service
                port:
                  number: 80
          - path: /webappb
            pathType: Prefix
            backend:
              service:
                name: apache-webapp-service
                port:
                  number: 80
