name: 01 - building blocks

on: push

jobs:
    echo-hello:
        runs-on: awsrunner
        steps:
            - name: Say hello
              run: echo "Hello, world"
    echo-goodbye:
        runs-on: awsrunner
        steps:
            - name: Failed Step
              run: |
                echo "I will succeed"
                exit 0
            - name: Say goodbye
              run: echo "Goodbye"
