name: 01 - building blocks

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up the TAG environment variable
        run: echo "TAG=$(git rev-parse --short=4 HEAD)" >> $GITHUB_ENV

      - name: Output Tag Value
        run: echo "$TAG"

      - name: List files in root (debugging)
        run: ls -la

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUBUSR }} 
          password: ${{ secrets.DOCKERHUBSECRET }}  
          
      - name: Build docker image for front1
        run: |
          cd front1
          docker build -t webapp1 .
          cd ..

      - name: Build docker image for front2
        run: |
          cd front2
          docker build -t webapp2 .
          cd ..

      - name: Tag docker images with $TAG
        run: |
          docker tag webapp1 ${{ secrets.DOCKERHUBREPO }}:webapp1${TAG}
          docker tag webapp2 ${{ secrets.DOCKERHUBREPO }}:webapp2${TAG}
          
      - name: Push docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUBREPO }}:webapp1${TAG}
          docker push ${{ secrets.DOCKERHUBREPO }}:webapp2${TAG}

      - name: Update Helm chart with new image tags
        run: |
          sed -i "s/tag:.*/tag: ${TAG}/" gh-actions-test/helmcharts

      - name: Commit updated Helm chart
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add gh-actions-test/helmcharts/values.yaml

          git commit -m "Update image tag to ${TAG} for webapp1 and webapp2"

      - name: Push updated Helm chart to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push
