name: 01 - building blocks

on: push

jobs:
    echo-hello:
        runs-on: self-hosted
        steps:
            - name: Say hello
              run: |
              - ls
              - ls -la
              - docker --version
    echo-goodbye:
        runs-on: self-hosted
        steps:
            - name: Failed Step
              run: |
                echo "I will succeed"
                exit 0
            - name: Say goodbye
              run: echo "Goodbye"
