name: 01 - building blocks

on:
  push:
    branches:
      - main

jobs:
  echo-hello:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files in root (debugging)
        run: ls -la

      - name: Build docker image
        run: |
          cd front1
          docker build -t webapp1 .
          cd front2
          docker build -t webapp2 .

