name: 01 - building blocks

on:
  push:
    branches:
      - main

jobs:
  echo-hello:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up the TAG environment variable
        run: echo "TAG=$(git rev-parse --short=4 HEAD)" >> $GITHUB_ENV

      # Optionally, output the tag value for debugging
      - name: Output Tag Value
        run: echo "Tag generated: ${{ env.TAG }}"

      - name: List files in root (debugging)
        run: ls -la

      - name: Build docker image for front1
        run: |
          cd front1
          docker build -t webapp1:${{ env.TAG }} .
          cd ..

      - name: Build docker image for front2
        run: |
          cd front2
          docker build -t webapp2:${{ env.TAG }} .
          cd ..
