name: 01 - building blocks

on:
  push:
    branches:
      - main

jobs:
  build-dreapp:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up the TAG environment variable
        run: echo "TAG=$(git rev-parse --short=4 HEAD)" >> $GITHUB_ENV

      - name: Output Tag Value
        run: echo "$TAG"

      - name: List files in root (debugging)
        run: ls -la

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUBUSR }}  # GitHub secret for Docker username
          password: ${{ secrets.DOCKERHUBSECRET }}  # GitHub secret for Docker password or token

      - name: Build docker image for front1
        run: |
          cd front1
          docker build -t webapp1 .
          cd ..

      - name: Build docker image for front2
        run: |
          cd front2
          docker build -t webapp2 .
          cd ..

      - name: Tag docker images with $TAG
        run: |
          docker tag webapp1 ${{ secrets.DOCKERHUBREPO }}:webapp1${TAG}
          docker tag webapp2 ${{ secrets.DOCKERHUBREPO }}:webapp2${TAG}

      - name: Push docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUBREPO }}:webapp1${TAG}
          docker push ${{ secrets.DOCKERHUBREPO }}:webapp2${TAG}
          
      - name: List files in the directory
        run: |
          ls -R helmcharts

      - name: Before updating values.yaml
        run: cat helmcharts/values.yaml

      - name: Update values.yaml with image tag
        run: |
          sed -i "s|webapp1: andrebik/s3andre:webapp1[^ ]*|webapp1: ${{ secrets.DOCKERHUBREPO }}:webapp1${TAG}|" helmcharts/values.yaml
          sed -i "s|webapp2: andrebik/s3andre:webapp2[^ ]*|webapp2: ${{ secrets.DOCKERHUBREPO }}:webapp2${TAG}|" helmcharts/values.yaml
     
      # - name: After updating values.yaml
      #   run: cat helmcharts/values.yaml
     
      # - name: Commit and push changes to values.yaml
      #   run: |
      #     git checkout --theirs helmcharts/values.yaml
      #     git config --local user.name "GitHub Actions"
      #     git config --local user.email "actions@github.com"
      #     git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      #     git stash -u
      #     git pull origin main --rebase || echo "Merge conflict detected"
      #     git checkout --theirs helmcharts/values.yaml
      #     git diff --exit-code || echo "Changes detected"

      #     # If there are changes, commit and push them
      #     if [[ -n "$(git diff --name-only)" ]]; then
      #       git add helmcharts/values.yaml
      #       git commit -m "Resolve merge conflict in values.yaml with remote version"
      #       git push origin main
      #     else
      #       echo "No changes to commit"
      #     fi
      #     git stash pop


  build-react:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust based on your Node.js version
  
      - name: Install dependencies
        run: |
            cd reactapp  # Ensure you're in the correct directory
            npm install

      - name: Set up the TAG environment variable
        run: echo "TAG=$(git rev-parse --short=4 HEAD)" >> $GITHUB_ENV

      - name: Output Tag Value
        run: echo "$TAG"

      - name: List files in root (debugging)
        run: ls -la

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUBUSR }}  # GitHub secret for Docker username
          password: ${{ secrets.DOCKERHUBSECRET }}  # GitHub secret for Docker password or token

      - name: Build docker image for reactapp
        run: |
          cd reactapp
          docker build -t reactapp .
          cd ..

      - name: Build docker image for backend
        run: |
          cd backend
          docker build -t backend .
          cd ..

      - name: Tag docker images with $TAG
        run: |
          docker tag reactapp ${{ secrets.DOCKERHUBREPO }}:reactapp${TAG}
          docker tag backend ${{ secrets.DOCKERHUBREPO }}:backend${TAG}

      - name: Push docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUBREPO }}:reactapp${TAG}
          docker push ${{ secrets.DOCKERHUBREPO }}:backend${TAG}
          
      - name: List files in the directory
        run: |
          ls -R helmcharts

      - name: Before updating values.yaml
        run: cat helmcharts/values.yaml

      - name: Update values.yaml with image tag
        run: |
          sed -i "/^reactapp:/s|:.*|: ${{ secrets.DOCKERHUBREPO }}:reactapp${TAG}|" helmcharts/values.yaml || echo "reactapp: ${{ secrets.DOCKERHUBREPO }}:reactapp${TAG}" >> helmcharts/values.yaml
          sed -i "/^backend:/s|:.*|: ${{ secrets.DOCKERHUBREPO }}:backend${TAG}|" helmcharts/values.yaml || echo "backend: ${{ secrets.DOCKERHUBREPO }}:backend${TAG}" >> helmcharts/values.yaml
     
      # - name: After updating values.yaml
      #   run: cat helmcharts/values.yaml

      # - name: Commit and push changes to values.yaml
      #   run: | 
      #     git stash -u
      #     git pull origin main --rebase || echo "Merge conflict detected"
      #     git stash pop
      #     git config --local user.name "GitHub Actions"
      #     git config --local user.email "actions@github.com"
      #     git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      #     git add helmcharts/values.yaml
      #     git commit -m "Update Helm chart with Docker image tag ${TAG}"
      #     git push origin main
      #     #git push
  build-push:
    runs-on: self-hosted
    needs: [build-dreapp, build-react] 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up the TAG environment variable
        run: echo "TAG=$(git rev-parse --short=4 HEAD)" >> $GITHUB_ENV

      - name: Update values.yaml with image tags
        run: |
          sed -i "s|webapp1: andrebik/s3andre:webapp1[^ ]*|webapp1: ${{ secrets.DOCKERHUBREPO }}:webapp1${TAG}|" helmcharts/values.yaml
          sed -i "s|webapp2: andrebik/s3andre:webapp2[^ ]*|webapp2: ${{ secrets.DOCKERHUBREPO }}:webapp2${TAG}|" helmcharts/values.yaml
          sed -i "/^reactapp:/s|:.*|: ${{ secrets.DOCKERHUBREPO }}:reactapp${TAG}|" helmcharts/values.yaml || echo "reactapp: ${{ secrets.DOCKERHUBREPO }}:reactapp${TAG}" >> helmcharts/values.yaml
          sed -i "/^backend:/s|:.*|: ${{ secrets.DOCKERHUBREPO }}:backend${TAG}|" helmcharts/values.yaml || echo "backend: ${{ secrets.DOCKERHUBREPO }}:backend${TAG}" >> helmcharts/values.yaml

      - name: Commit and push changes to values.yaml
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git pull 
          git stash pop || echo "Nothing to pop"
          git push origin main || echo "No changes to push"




