name: 01 - building blocks

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up the TAG environment variable
        run: echo "TAG=$(git rev-parse --short=4 HEAD)" >> $GITHUB_ENV

      - name: Output Tag Value
        run: echo "$TAG"

      - name: List files in root (debugging)
        run: ls -la

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUBUSR }}  # GitHub secret for Docker username
          password: ${{ secrets.DOCKERHUBSECRET }}  # GitHub secret for Docker password or token

      - name: Build docker image for front1
        run: |
          cd front1
          docker build -t webapp1 .
          cd ..

      - name: Build docker image for front2
        run: |
          cd front2
          docker build -t webapp2 .
          cd ..

      - name: Tag docker images with $TAG
        run: |
          docker tag webapp1 ${{ secrets.DOCKERHUBREPO }}:webapp1${TAG}
          docker tag webapp2 ${{ secrets.DOCKERHUBREPO }}:webapp2${TAG}

      - name: Push docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUBREPO }}:webapp1${TAG}
          docker push ${{ secrets.DOCKERHUBREPO }}:webapp2${TAG}
          
      - name: List files in the directory
        run: |
          ls -R helmcharts

      - name: Update values.yaml with image tags
        run: |
          sed -i "s|image: webapp1|image: ${{ secrets.DOCKERHUBREPO }}:webapp1${TAG}|" gh-actions-test/helmcharts/values.yaml
          sed -i "s|image: webapp2|image: ${{ secrets.DOCKERHUBREPO }}:webapp2${TAG}|" gh-actions-test/helmcharts/values.yaml

      - name: Commit and push changes to values.yaml
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add gh-actions-test/helmcharts/values.yaml
          git commit -m "Update Helm chart with Docker image tag ${TAG}"
          git push
