name: 01 - building blocks

on: push

jobs:
    echo-hello:
        runs-on: self-hosted
        steps:
            - name: build docker image
              run: |
               cd 
               cd front1 ../
    echo-goodbye:
        runs-on: self-hosted
        steps:
            - name: Failed Step
              run: |
                echo "I will succeed"
                exit 0
            - name: Say goodbye
              run: echo "Goodbye"
