name: 01 - building blocks

on:
  push:
    branches:
      - main

jobs:
  echo-hello:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up the TAG environment variable
      - name: Set up the TAG environment variable
        run: echo "TAG=$(git rev-parse --short=4 HEAD)" >> $GITHUB_ENV

      # Output the tag value for debugging
      - name: Output Tag Value
        run: echo "$TAG"

      - name: List files in root (debugging)
        run: ls -la

      - name: Build docker image for front1
        run: |
          cd front1
          docker build -t webapp1:${TAG} .
          cd ..

      - name: Build docker image for front2
        run: |
          cd front2
          docker build -t webapp2:${TAG} .
          cd ..
